services:
  mysql-demo:
    image: mysql:latest
    container_name: mysql-demo
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: demo